name: Unit Test

on:
  pull_request:
    types: [labeled]

jobs:
  country-unit-test:
    name: Country Unit Test
    if: github.event.label.name == 'run-unit-test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run evaluations
        uses: orq-ai/cli-evaluate@d859fb97687c2201f8dadba2145936ea968c0143
        with:
          pattern: "examples/src/lib/country-unit-test.eval.ts"
          orq-api-key: ${{ secrets.ORQ_API_KEY }}
